<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\Relations\HasOne;
use Illuminate\Database\Eloquent\Relations\MorphTo;
use App\Models\Concerns\BelongsToTenant;

class JournalEntry extends Model
{
    use HasFactory, BelongsToTenant;

    protected $fillable = [
        'date',
        'description',
        'sourceable_id',
        'sourceable_type',
        'status',
        'notes',
        'reversed_entry_id',
        'entry_type',
        'approved_by',
        'approved_at',
    ];

    protected $guarded = [
        'id',
        'tenant_id',
    ];

    protected $casts = [
        'date' => 'date',
        'approved_at' => 'datetime',
    ];

    public const STATUS_DRAFT = 'draft';
    public const STATUS_POSTED = 'posted';
    public const STATUS_VOID = 'void';

    public const ENTRY_TYPE_STANDARD = 'standard';
    public const ENTRY_TYPE_OPENING = 'opening';
    public const ENTRY_TYPE_REVERSAL = 'reversal';
    public const ENTRY_TYPE_ADJUSTING = 'adjusting';
    public const ENTRY_TYPE_CLOSING = 'closing';

    /**
     * Get the parent sourceable model (e.g., Sale, Purchase).
     */
    public function sourceable(): MorphTo
    {
        return $this->morphTo();
    }

    /**
     * Get the individual debit/credit transactions for the journal entry.
     */
    public function transactions(): HasMany
    {
        return $this->hasMany(Transaction::class);
    }

    /**
     * Get the reversed entry if this is a reversal.
     */
    public function reversedEntry(): BelongsTo
    {
        return $this->belongsTo(JournalEntry::class, 'reversed_entry_id');
    }

    /**
     * Get the reversing entry if this entry was reversed.
     */
    public function reversingEntry(): HasOne
    {
        return $this->hasOne(JournalEntry::class, 'reversed_entry_id');
    }

    /**
     * Get the user who approved this entry.
     */
    public function approvedBy(): BelongsTo
    {
        return $this->belongsTo(User::class, 'approved_by');
    }

    /**
     * Check if the journal entry is balanced.
     */
    public function isBalanced(): bool
    {
        $debits = $this->transactions->where('type', 'debit')->sum('amount');
        $credits = $this->transactions->where('type', 'credit')->sum('amount');
        return round($debits, 2) === round($credits, 2);
    }

    /**
     * Get the total debit amount.
     */
    public function getTotalDebitAttribute(): float
    {
        return $this->transactions->where('type', 'debit')->sum('amount');
    }

    /**
     * Get the total credit amount.
     */
    public function getTotalCreditAttribute(): float
    {
        return $this->transactions->where('type', 'credit')->sum('amount');
    }

    /**
     * Check if this entry can be reversed.
     */
    public function canBeReversed(): bool
    {
        return $this->status === self::STATUS_POSTED;
    }

    /**
     * Check if this entry can be voided.
     */
    public function canBeVoided(): bool
    {
        return $this->status === self::STATUS_POSTED;
    }

    /**
     * Scope for draft entries.
     */
    public function scopeDraft($query)
    {
        return $query->where('status', self::STATUS_DRAFT);
    }

    /**
     * Scope for posted entries.
     */
    public function scopePosted($query)
    {
        return $query->where('status', self::STATUS_POSTED);
    }

    /**
     * Scope for void entries.
     */
    public function scopeVoid($query)
    {
        return $query->where('status', self::STATUS_VOID);
    }

    /**
     * Scope for manual entries.
     */
    public function scopeManual($query)
    {
        return $query->whereNull('sourceable_type');
    }

    /**
     * Scope for auto-generated entries.
     */
    public function scopeAutoGenerated($query)
    {
        return $query->whereNotNull('sourceable_type');
    }
}